const express = require('express');
const verifToken = require('../middlewares/verifToken');
const verifRole = require('../middlewares/verifRole');
const router = express.Router();
const { signup, login, getProfile ,updateProfile,getAllProfile,getMyProfile,updateMyProfile} = require('../controllers/userController');
router.post('/signup', signup);
router.post('/login',login);
router.get('/profile/:id',getProfile);
router.get('/profiles',getAllProfile);
router.put('/profile',updateProfile);
router.get('/me', verifToken, getMyProfile);
router.put('/me',verifToken,updateMyProfile);
module.exports = router;