const express = require('express');
const verifToken = require('../middlewares/verifToken');
const router = express.Router();
const userController = require('../controllers/userController');
router.post('/signup',verifToken,userController.signup);
router.post('/login',userController.login);
router.get('/profile',userController.getProfile);
router.get('/profiles',userController.getAllProfile);
router.put('/profile',userController.updateProfile);
module.exports = router;